# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubec}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Hicks"]
  s.date = %q{2011-06-05}
  s.description = %q{Rubec is a set of parser combinators written in ruby... most of it was written in a single afternoon just to see if I could.}
  s.email = %q{ruby@simonhicks.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "docs/lib/example.html",
    "docs/lib/extensions/fixnum.html",
    "docs/lib/extensions/object.html",
    "docs/lib/extensions/range.html",
    "docs/lib/extensions/regexp.html",
    "docs/lib/extensions/string.html",
    "docs/lib/rubec.html",
    "docs/lib/rubec/state.html",
    "lib/example.rb",
    "lib/extensions/fixnum.rb",
    "lib/extensions/object.rb",
    "lib/extensions/range.rb",
    "lib/extensions/regexp.rb",
    "lib/extensions/string.rb",
    "lib/rubec.rb",
    "lib/rubec/state.rb"
  ]
  s.homepage = %q{http://github.com/simonhicks/rubec}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A set of parser combinators for ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
  end
end

